### ISSUE TITLE
License

### ISSUE THREAD

**Issue by REAS** [voidlab/diversity-statement#1]
Did the lab discuss the license applied to the statement? I think a Creative Commons license is more appropriate because the license is a piece of text, rather than source code. Where does a "text" start and "source code" stop from a legal point of view? I don't know, but I think it might be good to discuss and get consultation.

**Comment by kjhollen** [comment]
Ah, we didn't discuss the license at the time of writing. Hsinyu has updated to CC-SA 4.0. Now it should be easier & more compact for instructors to include in their own syllabi...

**Comment by xinemata** [comment]
I believe this has been resolved. Closing the issue.
